### ISSUE TITLE
`view.floatingButtonAction` in onCreate function in List Fragment is not recognized

### ISSUE THREAD

**Issue by kevinadhiguna** [roshan129/RoomDbStevedzaK#1]
Hello, I am following the same tutorial but am stuck at second video which is ROOM Database - #2 Insert Data. It is because I cannot access any views within List fragment. When I type view.floatingActionButton, it doesn't recognize what floatingActionButton is. Could you please give me a clue ?

![image](https://user-images.githubusercontent.com/43397636/115494980-e1aaf580-a290-11eb-867b-ea67e021c949.png)

Video Source : [ROOM Database - #2 Insert Data | Android Studio Tutorial on 4:50](https://youtu.be/UBCAWfztTrQ?t=288)

Thank you

**Comment by roshan129** [comment]
I saw your project. You have used view binding to access views now. So should I close this issue?

**Comment by kevinadhiguna** [comment]
Thank you, I was able to solve the issue with viewBinding. However, I find another problem with `insertDataToDatabase()` function in [AddFragment.kt](https://github.com/kevinadhiguna/kotlin-room-database/blob/master/app/src/main/java/com/example/kotlinroomdatabase/fragments/add/AddFragment.kt).

![image](https://user-images.githubusercontent.com/43397636/115649388-65c4b200-a351-11eb-9eb9-5b578882ffbd.png)

The error says : Unresolved reference: addFirstName_et

Actually I use `addBtn` instead of `add_btn` because `add_btn` was undefined and `addBtn` occurred in autocomplete. What I wonder is that I named it `add_btn` in `fragment_add.xml` : 

![image](https://user-images.githubusercontent.com/43397636/115649020-b7207180-a350-11eb-8bcc-43884400fbb8.png)

Here is the repo : https://github.com/kevinadhiguna/kotlin-room-database

Sorry to bother you, I really appreciate your help.

**Comment by roshan129** [comment]
Yes that's something view binding does when it auto generates binding classes. FragmentAddBinding is the auto generated binding class in this case.  So, add_btn is converted to addBtn, similarly something like linearLayout_toolbar will be converted to linearLayoutToolbar. It avoids the underscore. There is nothing to worry about, thats just how view binding works. 
Also addFirstName_et will be converted to addFirstNameEt.

**Comment by kevinadhiguna** [comment]
![image](https://user-images.githubusercontent.com/43397636/115675222-9b30c600-a378-11eb-8248-00296dff5000.png)

Thank you, the issue seems to be resolved. You are awesome !
